all:
	cd Global && $(MAKE)
	cd Pi     && $(MAKE)
	cd Sump   && $(MAKE)

clean:
	cd Global && $(MAKE) clean
	cd Pi     && $(MAKE) clean
	cd Sump   && $(MAKE) clean

# have a look at https://www.gnu.org/software/make/manual/html_node/index.html#SEC_Contents
